### ISSUE TITLE
acf-rf-opt not adding 'option' to while loop

### ISSUE THREAD

**Issue by simonwimell** [emaildano/acf-snippets#2]
acf-rf-opt adds: 

``` php
<?php if ( have_rows('field_name', 'option') ): ?>
    <ul>
        <?php while ( have_rows('field_name') ) : the_row(); ?>
            <li><?php the_sub_field('field_name'); ?></li>
        <?php endwhile; ?>
    </ul>
<?php endif; ?>
```

It should be:

``` php
<?php if ( have_rows('field_name', 'option') ): ?>
    <ul>
        <?php while ( have_rows('field_name', 'option') ) : the_row(); ?>
            <li><?php the_sub_field('field_name'); ?></li>
        <?php endwhile; ?>
    </ul>
<?php endif; ?>
```

**Comment by emaildano** [comment]
@simonwimell thanks for the feedback. I haven't updated this plugin in a while. This gives me reason to review, fix and push out a new version.

**Comment by andrewmartin** [comment]
@emaildano @simonwimell 

Or, you could [merge my PR](https://github.com/emaildano/acf-snippets/pull/3) 😄 . I just added this call and also added a couple other helpful snippets.

**Comment by emaildano** [comment]
@simonwimell all good, merged the PR so you're set
